Merge branch 'main' of https://github.com/asgatech20/AndroidDateFormatter into development
asgatech20/AndroidDateFormatter pull request #1
Opened 2022-01-16 10:53 UTC by Ahmed-Saber-25

2022-01-16 12:30 UTC, asgatech20 requested changes
- Please Add Readme file that should contain docs of the component.
- Provide an example of using the component in the example app.
- Take care of functions naming.
- Add Test functions for the non acceptable cases in the DateFormatterUtilTest class.

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +     */
Fix the documentation text as doesn't describe the function usage correctly.

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +     * @param format A String represents input date format
Change to be '* @param format A String represents the required format'

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +    //enum dateformat
Remove this comment and write usage documentation for the object

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +            calendar.timeInMillis = from.time
Convert to separate function

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +            )
Concert to separate function

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +                .withChronology(iso).toLocalDate()
Convert to separate function with return type

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +     * @usage this function is used to convert LocalDateTime object to hijri date String
change LocalDateTime  to the correct type that function already accepts

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +    }
Refactor this function to be more usable as from the function body it is seen that user can't figure out he must pass a dateString with specific format that the function accepts "yyyy-MM-dd'T'HH:mm:ss"

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +    }
Refactor this function to be more usable as from the function body it is seen that user can't figure out he must pass a dateString with specific format that the function accepts "yyyy-MM-dd'T'HH:mm:ss"

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +    fun compareDates(fromDate: String , toDate: String): Boolean {
Use an appropriate function naming as the current function name doesn't represent the actual usage of the function.

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +    }
First: Use an appropriate function naming as the current function name doesn't represent the actual usage of the function.
Second: This function is not null safe (if user passes a dateString that doesn't have hours and minutes format, the function will fail and application will crash), so it needs to be refactored.

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +    }
Add a param that makes user capable to get the current date with a certain format.

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +    }
First: Use an appropriate function naming as the current function name doesn't represent the actual usage of the function.
Second: The user can't figure out he must pass a dateString with specific format that the function accepts "yyyy/MM/dd - hh:mm:ss a"
=> for example: what should happen if he passes a dateString with format of  "yyyy-MM-dd'T'HH:mm:ss" ?

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/test/java/com/example/dateformatter/DateFormatterUtilTest.kt
> +    }
The data of 12 / 01 /2021 should return 9 / 6 / 1443 in Higri not 8 / 6 / 1443 
Fix the function in your formatter class

2022-01-16 12:30 UTC, asgatech20 commented on dateformatterutil/src/test/java/com/example/dateformatter/DateFormatterUtilTest.kt
> +class DateFormatterUtilTest{
General Comment:
Add Test functions for the non acceptable cases.

2022-01-16 14:03 UTC, Ahmed-Saber-25 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +     */
resolved

2022-01-24 15:19 UTC, Ahmed-Saber-25 commented
solve commits

2022-01-24 16:19 UTC, asgatech20 requested changes, later dismissed
- Try to use exceptions to handle critical failures.
- Write test cases for the wrong scenarios.

2022-01-24 16:19 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
>       * @return A Date that represents the localDate is islamic or normal date
correct the documentation text

2022-01-24 16:19 UTC, asgatech20 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
>              .withChronology(iso).toLocalDate()
convert to minusDays(1)

2022-01-25 11:20 UTC, IbrahimAli2017 commented on README.md
> +     this module is used to convert date object to string value with specific formate ,hijri-to-gregorian and vice versa and extract any part of date you need
can convert from string to date or not?

2022-01-25 11:20 UTC, IbrahimAli2017 commented on README.md
> +* `dateParser` **{StandardDateParser}** mandatory input
what is dateParser?
should define the DateParser before starting describe  the functions

2022-01-25 11:20 UTC, IbrahimAli2017 commented on README.md
> +
add description about the example

2022-01-25 11:20 UTC, IbrahimAli2017 commented on README.md
> +
add description about example

2022-01-25 11:20 UTC, IbrahimAli2017 commented on README.md
> +val date = DateFormatterUtil.convertStringToDate(
please build Date Object using calendar not from convertStringToDate
this example to show how convert date to string not string to another string

2022-01-25 11:20 UTC, IbrahimAli2017 commented on README.md
> +
add description about the example

2022-01-25 11:20 UTC, IbrahimAli2017 commented on README.md
> +
the same comment

2022-01-25 11:20 UTC, IbrahimAli2017 commented on README.md
> +
same comment

2022-01-25 11:20 UTC, IbrahimAli2017 commented on README.md
> +### fun isFutureDate(fromDate: String, toDate: String): Boolean
rename to be is after
change fromDate to be firstDate
change toDate to be secondDate

2022-01-25 11:20 UTC, IbrahimAli2017 commented on README.md
> +
add contributors

2022-01-25 11:20 UTC, IbrahimAli2017 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +            ""
this for what?

2022-01-25 11:20 UTC, IbrahimAli2017 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +    fun getCurrentData(dateParser: StandardDateParser): String {
rename the function to be getCurrentDate not Data

2022-01-25 11:20 UTC, IbrahimAli2017 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +            return if (hour.toInt() in 13..23 || time.contains("PM")) "$hour:$minute PM" else "$hour:$minute AM"
what if the string in ar lang the contains function will be false 
PM and AM good for en Lang we should support AR Lang

2022-01-25 11:20 UTC, IbrahimAli2017 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +    fun isFutureDate(fromDate: String, toDate: String): Boolean {
rename the function
isFutureDate => isAfter
fromDate => firstDate
toDate => secondDate

2022-01-25 11:20 UTC, IbrahimAli2017 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +            Date(toDate).after(Date(fromDate))
what is the deference between 
Date(toDate) & dateParser.parser.parse(from)

2022-01-25 11:20 UTC, IbrahimAli2017 commented on dateformatterutil/src/test/java/com/example/dateformatter/DateFormatterUtilTest.kt
> +    fun getDateFromPmAmHoursMin_return_invalid_result_when_passing_invalid_params() {
you should test AR Lang

2022-01-25 11:20 UTC, IbrahimAli2017 commented on dateformatterutil/src/test/java/com/example/dateformatter/DateFormatterUtilTest.kt
> +    fun getDateFromPmAmHoursMin_return_valid_result_when_passing_valid_params() {
should test AR Lang

2022-01-25 13:47 UTC, Ahmed-Saber-25 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +            Date(toDate).after(Date(fromDate))
first : here we restricted to date string and it is deprecated
 @Deprecated
    public Date(String s) {
        this(parse(s));
    }

second : here we can pass format and local 
SimpleDateFormat("dd.MM.yyyy HH:mm:ss",Locale.ENGLISH).parse(dateString)

2022-01-25 14:27 UTC, IbrahimAli2017 commented on dateformatterutil/src/main/java/com/example/dateformatter/DateFormatterUtil.kt
> +    fun isAfterDate(firstDate: String, secondDate: String): Boolean {
it should use the previous functions to get date

2022-01-25 15:19 UTC, IbrahimAli2017 approved these changes

2022-01-25 15:20 UTC, merged